## 2.1 数据操作

In [ ]:
import torch

In [ ]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
x.shape

torch.Size([12])

In [ ]:
x.numel()

12

In [ ]:
len(x)

12

In [ ]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
torch.randn(3, 4)

tensor([[-0.5095,  0.0904, -0.3382, -0.5509],
        [ 1.1665, -0.5478, -0.6895,  0.3604],
        [ 1.6703, -0.4970, -1.3684, -0.0601]])

In [ ]:
torch.tensor([[1.0,2,3,4],[2,3,4,5],[1,2,3,4]])

tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.],
        [1., 2., 3., 4.]])

In [ ]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2.0, 2, 2, 2])
x + y, x - y, x * y, x / y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [ ]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

张量连接

In [ ]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [ ]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
X.sum()

tensor(66.)

### 2.1.3 广播机制

In [ ]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [ ]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 2.1.4 索引和切片

In [ ]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [ ]:
# index replacement
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
# row slicing replacement
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [ ]:
before = id(Y)
Y = Y + X
id(Y) == before

False

### 2.1.5 节省内存
原地分配

In [ ]:
Z = torch.zeros_like(Y)
print(id(Z))
Z[:] = X + Y
print(id(Z))

127672696693024
127672696693024


In [ ]:
before = id(X)
X += Y
print(id(X) == before)
X[:] = Y + X
print(id(X) == before)

True
True


### 2.1.6 转换为其他Python对象 

In [ ]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [ ]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

# 2.2 数据预处理

In [ ]:
import os
os.makedirs('data', exist_ok=True)
data_file = 'data/houce_tiny.csv'
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA, Pave,127500\n')
    f.write('2, NA,106000\n')
    f.write('4, NA,178100\n')
    f.write('NA, NA,140000\n')

In [ ]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley  Bathrooms   Price
0         2   NaN       1.00  127500
1         3  Grvl       2.00  106000
2         4  Pave       1.75  178000


In [4]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
# 均值填充
inputs = inputs.fillna(inputs.mean())
inputs

TypeError: unsupported operand type(s) for +: 'int' and 'str'

# 2.5 自动微分

In [ ]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [ ]:
x.requires_grad_(True)
x.grad

In [ ]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [ ]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [ ]:
x.grad.zero_()
y= x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])